force-app/main/default/objects/Physician__c/Physician__c.object-meta.xml
<CustomObject>
    <label>Physician</label>
    <nameField>
        <displayFormat>PID-{0000}</displayFormat>
        <label>PID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Physicians</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Physician__c/fields/Physician__c.field-meta.xml
<CustomField>
    <fullName>Physician__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Physician Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Physicians</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Physician__c/fields/Specialization__c.field-meta.xml
<CustomField>
    <fullName>Specialization__c</fullName>
    <label>Specialization Name</label>
    <referenceTo>Specialization__c</referenceTo>
    <relationshipLabel>Physicians</relationshipLabel>
    <relationshipName>Physicians</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Specialization__c/Specialization__c.object-meta.xml
<CustomObject>
    <label>Specialization</label>
    <nameField>
        <label>Specialization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specializations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Toptal_WrapperUtil.cls
/**
* Util wrapper class for booking appoitments
*
* @author  Ramamoorthy D
* @version 1.0
* @date   06/02/2022 
*/

public with sharing class Toptal_WrapperUtil {
    public class NewPatient {
        @AuraEnabled
        public String name{get; set;}
        @AuraEnabled
        public String email{get; set;}
        @AuraEnabled
        public Decimal age{get; set;}
        @AuraEnabled
        public String phoneNumber{get; set;}
        @AuraEnabled
        public String patientAddress{get; set;}
    }

    public class PatientCreationDetails {
        @AuraEnabled
        public Boolean isPatientCreated {get; set;}
        @AuraEnabled
        public String referenceNo {get; set;}
    }

    public class EventAvailability {
        public EventAvailability(String timeSlot, String availability){
            this.timeSlot = timeSlot;
            this.availability = availability;
        }
        @AuraEnabled
        public String timeSlot {get; set;}
        @AuraEnabled
        public String availability {get; set;}
    }

    public class AppointmentScreen {
        @AuraEnabled
        public List<SpecializationDetails> specializationList{get;set;}
    }

    public class SpecializationDetails {
        @AuraEnabled
        public Specialization__c specialization{get;set;}
        @AuraEnabled
        public List<Physician__c> physicianList{get;set;}
    }

    public class CalendarDetails {
        @AuraEnabled
        public String physicianName {get; set;}
        @AuraEnabled
        public String physicianEmail {get; set;}
        @AuraEnabled
        public String selectedDate {get; set;}
        @AuraEnabled
        public String selectedTimeSlot {get; set;}
        @AuraEnabled
        public String selectedTime {get; set;}
    }

    public class EventStatus {
        @AuraEnabled
        public List<EventAvailability> evtAvailabilityList {get; set;} 
    }

    public class CalendarResponse{
        @AuraEnabled
        public Boolean isEventCreated {get; set;}
        @AuraEnabled
        public Integer statusCode {get; set;}
    }
}