force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>Ref.No-{0000}</displayFormat>
        <label>Reference ID No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient Name</label>
    <referenceTo>Patient__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Physician__c.field-meta.xml
<CustomField>
    <fullName>Physician__c</fullName>
    <label>Physician Name</label>
    <referenceTo>Physician__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appointment_History__c/Appointment_History__c.object-meta.xml
<CustomObject>
    <label>Appointment History</label>
    <nameField>
        <displayFormat>AP.NO-{0000}</displayFormat>
        <label>Appointment number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment_History__c/fields/Appointment_ID__c.field-meta.xml
<CustomField>
    <fullName>Appointment_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Appointment ID</label>
    <referenceTo>Appointment__c</referenceTo>
    <relationshipLabel>Appointments History</relationshipLabel>
    <relationshipName>Appointments_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment_History__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient Name</label>
    <referenceTo>Patient__c</referenceTo>
    <relationshipLabel>Appointments History</relationshipLabel>
    <relationshipName>Appointments_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Patient__c/Patient__c.object-meta.xml
<CustomObject>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <label>Age</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Email-ID</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Phone_number__c.field-meta.xml
<CustomField>
    <fullName>Phone_number__c</fullName>
    <label>Phone number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Physician__c/Physician__c.object-meta.xml
<CustomObject>
    <label>Physician</label>
    <nameField>
        <displayFormat>PID-{0000}</displayFormat>
        <label>PID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Physicians</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Physician__c/fields/Physician__c.field-meta.xml
<CustomField>
    <fullName>Physician__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Physician Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Physicians</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Physician__c/fields/Show_Calendar__c.field-meta.xml
<CustomField>
    <fullName>Show_Calendar__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Calendar</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Physician__c/fields/Specialization__c.field-meta.xml
<CustomField>
    <fullName>Specialization__c</fullName>
    <label>Specialization Name</label>
    <referenceTo>Specialization__c</referenceTo>
    <relationshipLabel>Physicians</relationshipLabel>
    <relationshipName>Physicians</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Specialization__c/Specialization__c.object-meta.xml
<CustomObject>
    <label>Specialization</label>
    <nameField>
        <label>Specialization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specializations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Specialization__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/Toptal_ClinicHandler.cls
/**
* Handler class for booking appoitments
*
* @author  Ramamoorthy D
* @version 1.0
* @date   06/02/2022 
*/

public with sharing class Toptal_ClinicHandler {

   /**
   * This method is used to fetch both Specialization
   * and Physicians records
   * @return Toptal_WrapperUtil.AppointmentScreen
   */
    @AuraEnabled(cacheable=true)
    public static Toptal_WrapperUtil.AppointmentScreen fetchAppointmentScreenDetails() {
        Toptal_WrapperUtil.AppointmentScreen apptmtDetails = new Toptal_WrapperUtil.AppointmentScreen();
        List<Specialization__c> specializationsList = [ SELECT Id, Name, Price__c, (SELECT Id, Physician__c, Physician__r.Name, Physician__r.Email, Show_Calendar__c, Specialization__r.Name from Physicians__r) FROM Specialization__c ];
        List<Toptal_WrapperUtil.SpecializationDetails> specializationDetailsList = new List<Toptal_WrapperUtil.SpecializationDetails>();
        for(Specialization__c objSpecialization : specializationsList){
            Toptal_WrapperUtil.SpecializationDetails specializationDetails = new Toptal_WrapperUtil.SpecializationDetails();
            specializationDetails.specialization = objSpecialization;            
            specializationDetails.physicianList = objSpecialization.Physicians__r;
            specializationDetailsList.add(specializationDetails);
        }
        apptmtDetails.specializationList = specializationDetailsList;
        return apptmtDetails;
    }  
    
    /**
    * This method is used to create appointment for old patient
    * @param String - Name of the patient
    * @param String - Id of the physician
    * @return String - newly created appointment name
    */
    @AuraEnabled
    public static String createAppointmentForOldPatient(String patientId, String physicianId){
        if(String.isNotBlank(patientId) && String.isNotBlank(physicianId)){
            try {
                Appointment__c appointment = createAppointment(patientId,physicianId);            
                logAppointmentHistory(patientId, appointment.Id);
                if(appointment != null) {
                    return [SELECT Id, Name FROM Appointment__c WHERE Id = :appointment.Id].Name;
                }
            } catch (Exception ex) {
                throw ex;
            }
        }
        return 'Something went wrong';
    }
    
    /**
    * This method is used to create appointment for new patient
    * @param String - Name of the patient
    * @param String - Id of the appointnment
    * @return Toptal_WrapperUtil.PatientCreationDetails - newly created patient details
    */
    @AuraEnabled
    public static String createAppointmentForNewPatient(Toptal_WrapperUtil.NewPatient newPatientDetails, String physicianId){
        if(newPatientDetails != null) {
            Patient__c patient = createPatient(newPatientDetails);
            Appointment__c appointment = createAppointment(patient.Id,physicianId);
            LogAppointmentHistory(patient.Id, appointment.ID);
            if(appointment != null) {
                return [SELECT Id, Name FROM Appointment__c WHERE Id = :appointment.Id].Name;
            }
        }
        return '';
    }
    
    /**
    * This reusable method is used to create appointment history record
    * @param String - Name of the patient
    * @param String - Id of the appointnment
    * @return Appointment__c - newly created appointment record
    */
    public static void logAppointmentHistory(String patientId, String appointmentId){
        Appointment_History__c appointmentHistory = new Appointment_History__c();
        appointmentHistory.Patient__c = [SELECT Id, Name FROM Patient__c WHERE ID =: patientId LIMIT 1].Id;
        appointmentHistory.Appointment_ID__c = [SELECT ID, NAME FROM Appointment__c WHERE Id =: appointmentId LIMIT 1].Id;
        INSERT appointmentHistory;
    }
    
    /**
    * This reusable method is used to create patient record
    * @param Toptal_WrapperUtil.NewPatient - Details of the new patient
    * @return Patient__c - newly created Patient record
    */
    public static Patient__c createPatient(Toptal_WrapperUtil.NewPatient newPatientDetails){
        Patient__c patient = new Patient__c();
        patient.Name = newPatientDetails.name;
        patient.Age__c = newPatientDetails.age;
        patient.Email_Id__c = newPatientDetails.email;
        patient.Phone_number__c = newPatientDetails.phoneNumber;
        patient.Address__c = newPatientDetails.patientAddress;
        insert patient;
        if(patient != null) {
            return patient;
        }
        return patient;
    }
    
    /**
    * This reusable method is used to create appointment record
    * @param String - Name of the patient
    * @param String - Email Id of the patient
    * @return Appointment__c - newly created appointment record
    */
    public static Appointment__c createAppointment(String patientId,String physicianId){
        Appointment__c appointment = new Appointment__c();
        appointment.Patient__c = patientId;
        appointment.Physician__c =  physicianId;
        insert appointment;
        if(appointment != null) {
            return appointment;
        }
        return appointment;
    }
    
    /**
    * This method is used to fetch patient details in existing patient screen
    * @param String - Name of the patient
    * @param String - Email Id of the patient
    * @return List<Patient__c>
    */
    @AuraEnabled
    public static List<Patient__c> fetchPatientDetails(String patientName, String patientEmail) {
        List<Patient__c> patientList = new List<Patient__c>();
        String sQuery = '';
        if(String.isNotBlank(patientName) && String.isNotBlank(patientEmail)) {
            sQuery = 'SELECT Id, Name, Email_Id__c FROM  Patient__c WHERE Name LIKE ' + '\'%' + patientName + '%\'' + ' AND Email_Id__c LIKE ' + '\'%' + patientEmail + '%\'';
        }
        else if(String.isNotBlank(patientName)) {
            sQuery = 'SELECT Id, Name, Email_Id__c FROM  Patient__c WHERE Name LIKE ' + '\'%' + patientName + '%\'';
        } 
        else if(String.isNotBlank(patientEmail)) {
            sQuery = 'SELECT Id, Name, Email_Id__c FROM  Patient__c WHERE Email_Id__c LIKE ' + '\'%' + patientEmail + '%\'';
        }
        patientList = Database.Query(sQuery);
        if(patientList.size() > 0) {
            return patientList;
        }
        return patientList;
    }
  
}